### ISSUE TITLE
Name-registry: Replace use of `str[8]` with `String`

### ISSUE THREAD

**Issue by K1-R1** [FuelLabs/sway-applications#683] opened 2023-05-22 14:53 UTC
In `name-registry/project/contracts/registry-contract/src/main.sw`; the use of `str[8]` can now be replaced with the `String` type in [sway-libs](https://github.com/FuelLabs/sway-libs/tree/master/libs/strings/string).

**Comment by Braqzen** [comment] 2023-05-22 21:38
This is a duplicate of #450 and that issue should be edited to use `StorageString` because we need to maintain state. `String` is a heap type, similar to `Bytes` so we cannot store them. Feel free to update that issue description.

**Closed** 2023-05-23 12:13 UTC
Labels: Improvement, App: Name Registry
